name: CMake

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ rpm

    - name: Configure project
      run: cmake -H. -B_build

    - name: Build project
      run: cmake --build _build

    - name: Create package
      run: |
        cd _build
        cpack -G "TGZ"
